name: WFF Parse

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
	strategy:
      matrix:
	    node_version: [14.x, 12.x, 10.x]
	steps:
	  - uses: actions/checkout@v1
	  - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
	  - name: npm ci
	    run: |
		  npm ci
	  - name: npm test
	    run: |
		  npm test
		env:
		  CI: true

